theme: minima
title: lab 
author: Tomio 
email: tomioy@microsoft.com
description: > ここに説明を書く
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle


show_excerpts: true # set to false to remove excerpts on the homepage
